# 应用服务 WEB 访问端口
server.port: 8089
spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
#  datasource:
#    username: root
#    password: wain9425
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver